export const DATA = [
  {
    title: 'Сайт многоквартирного дома',
    subtitle: 'Технологии: HTML, CSS, JS, Webpack, Express.js',
    description: 'Одностраничный сайт',
    link: 'http://a100a.ru',
    image: '../images/romanoff.jpg',
  },
  {
    title: 'Сайт оконной компании',
    subtitle: 'Технологии: WordPress, JS',
    description: 'Многостраничный сайт',
    link: 'https://stvorka34.ru',
    image: '../images/stvorka.png',
  },
  {
    title: 'Дипломный проект Яндекс.Практикум',
    subtitle: 'Технологии: HTML, CSS, JS, Webpack, Express.js',
    description: 'Сервис по поиску новостей',
    link: 'https://anton-zm.github.io/news-frontend/',
    image: '../images/diplom.png',
  },
  {
    title: 'Учебный проект Яндекс.Практикум',
    subtitle: 'Технологии: JS',
    link: 'https://anton-zm.github.io/mesto-sprint11/',
    description: 'Учебный сервис сохранения карточек',
    image: '../images/mesto.png',
  },
  {
    title: 'Учебный проект Яндекс.Практикум',
    subtitle: 'Технологии: RegExp',
    link: 'https://anton-zm.github.io/sprint-10/',
    description: 'Регулярные выражения',
    image: '../images/regexp.png',
  },
  {
    title: 'Учебный проект Яндекс.Практикум',
    subtitle: 'Технологии: HTML, CSS',
    link: 'https://anton-zm.github.io/sprint-4/',
    description: 'Адаптивная вёрстка',
    image: '../images/russia.png',
  },
  {
    title: 'Учебный проект Яндекс.Практикум',
    subtitle: 'Технологии: HTML, CSS',
    link: 'https://anton-zm.github.io/sprint-2/',
    description: 'Десктопная вёрстка',
    image: '../images/study.png',
  },
];
